name: tsai
channels:
- tsai
- fastai
- pytorch
- defaults
dependencies:
- fastai>=2.5.2
- PyWavelets>=1.1.1
- numba>=0.53
- conda-forge::sktime>=0.7.0
- conda-forge::pyts>=0.11.0
- conda-forge::imbalanced-learn>=0.8.0
- conda-forge::tsfresh>=0.18.0
- pytorch>=1.7.0